version: '3.3'

services:
  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - "postgres"
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
      PGDATA: /data/postgres
    networks:
      - default
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      SERVER_MODE: "TRUE"
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    links:
      - postgres:postgres
    networks:
      - default
    restart: always
    depends_on:
      - "postgres"

volumes:
  db-data:
  postgres:
  pgadmin: