# Generated by Django 3.0.7 on 2020-07-13 09:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200713_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
