# Generated by Django 3.0.7 on 2020-07-14 07:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200713_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sortname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20)),
                ('username', models.CharField(default='', max_length=200, unique=True)),
                ('email_address', models.EmailField(default='', max_length=200, unique=True)),
                ('mobile_no', models.CharField(default='', max_length=15, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Countrie')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_WishList',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('Review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default='0')),
                ('review', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Addres',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('alternative_mobile', models.CharField(blank=True, max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('address', tinymce.models.HTMLField()),
                ('city', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Office')], default='HOME', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Countrie')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.State')),
            ],
        ),
    ]
