# Generated by Django 3.0.7 on 2020-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_countrie_customer_customer_addres_customer_review_customer_wishlist_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrie',
            name='pincode',
        ),
        migrations.AddField(
            model_name='countrie',
            name='phonecode',
            field=models.IntegerField(default='0'),
        ),
    ]
