# Generated by Django 3.0.7 on 2020-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
