# Generated by Django 3.0.7 on 2020-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_customer_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_addres',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
