# Generated by Django 3.0.7 on 2020-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200717_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='old_currency_rate',
            field=models.FloatField(default='0.0', max_length=5),
        ),
    ]
