# Generated by Django 3.0.7 on 2020-07-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productprice_old_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review',
            name='image',
            field=models.ImageField(null=True, upload_to='shop/images/review'),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=15)),
                ('product_total', models.FloatField(default='')),
                ('product_gst_amount', models.FloatField(default='')),
                ('product_payable_amount', models.FloatField(default='')),
                ('shipping_charge', models.IntegerField(default='')),
                ('product_currency', models.CharField(choices=[('INR', 'India Rupee'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('EUR', 'Euro')], default='INR', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUND', 'Refund')], default='Unpaid', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer_Addres')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer_review',
            name='order',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='shop.Customer_Order'),
        ),
    ]
