# Generated by Django 3.0.7 on 2020-07-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200723_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer_Order'),
        ),
    ]
