# Generated by Django 3.0.7 on 2020-07-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200723_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Addres',
            new_name='CustomerAddres',
        ),
    ]
