# Generated by Django 3.0.7 on 2020-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderitem_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_latest_status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('PKD', 'Packed'), ('SPD', 'Shipped'), ('DLD', 'Delivered'), ('CLD', 'Canceled')], default='ORD', max_length=15),
        ),
    ]
