# Generated by Django 3.0.7 on 2020-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_customerorder_order_latest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_latest_status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('PKD', 'Packed'), ('SPD', 'Shipped'), ('OFD', 'Out For Delivery'), ('DLD', 'Delivered'), ('CLD', 'Canceled')], default='ORD', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('PKD', 'Packed'), ('SPD', 'Shipped'), ('OFD', 'Out For Delivery'), ('DLD', 'Delivered'), ('CLD', 'Canceled')], default='ORD', max_length=20),
        ),
    ]
