# Generated by Django 3.0.7 on 2020-07-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200723_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
