# Generated by Django 3.0.7 on 2020-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200724_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='shop/images/review'),
        ),
    ]
