# Generated by Django 3.0.7 on 2020-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_tag',
            field=models.TextField(default=''),
        ),
    ]
