# Generated by Django 3.0.7 on 2020-07-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_customerorder_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_send_order_status',
            field=models.BooleanField(default=True),
        ),
    ]
