# Generated by Django 3.0.7 on 2020-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200728_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='send_email_status',
            field=models.BooleanField(default=False),
        ),
    ]
